Feature/us040 login system
kamil3197/agile-project-TEAMB pull request #12
Opened 2023-08-10 10:00 UTC by japilarski

2023-08-10 13:39 UTC, leszekgu requested changes
Overall it should work just few changes to make and maybe some more checking will happen during second (authorisation story)

2023-08-10 13:39 UTC, leszekgu commented on product-backend/scripts/create_db.sql
> +    email varchar(64) NOT NULL UNIQUE,
email field should be longer, google says typical address is 50-125 characters let's use the latter

2023-08-10 13:39 UTC, leszekgu commented on product-backend/scripts/create_db.sql
> +CREATE TABLE IF NOT EXISTS Tokens (
you shouldn't need this table

2023-08-10 13:39 UTC, leszekgu commented on product-backend/scripts/db_build.sh
> +rm -f create_db_exe.sql
👍

2023-08-10 13:39 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/api/AuthService.java
> +        }
You can invert this if and apply a rule of 'fail fast' 
```suggestion
        if (!authResult) {
            throw new WrongPasswordException();
        }
          Algorithm algorithm = Algorithm.HMAC256("NOT_HARDCODED_SECRET"); // TODO: change to asynchronous algorithm
          long now = System.currentTimeMillis();
          long expiry = now + 3_600_000;
          String jwtToken = JWT.create()
                  .withSubject(userDb.getEmail())
                  .withClaim("user_id", userDb.getId())
                  .withClaim("user_email", userDb.getEmail())
                  .withClaim("user_role", userDb.getRole())
                  .withIssuedAt(new Date(now))
                  .withExpiresAt(new Date(expiry))
                  .sign(algorithm);

          return jwtToken;
```

2023-08-10 13:39 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/db/AuthDao.java
> +    public Token getToken(String email) throws FailedToGetTokenException {
There is no need to store the tokens. Authorisation part will use data form JWT and verify whether it was tampered with based on signed key.

2023-08-10 13:39 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/resources/AuthController.java
> +            return Response.ok("JWT token").cookie(jwtCookie).build();
return the token as part of the JSON body.
Only frontend need to pass it as a cookie to the browser.

2023-08-10 13:39 UTC, leszekgu commented on product-backend/src/test/java/service/AuthServiceTest.java
> +        assertEquals(result, jwtToken);
I'm surprised it's not failing on difference related to Date IssueAt and ExpiresAt

2023-08-10 13:39 UTC, leszekgu commented on product-backend/src/test/java/service/AuthServiceTest.java
> +
you can remove those empty lines ;)

2023-08-10 13:39 UTC, leszekgu commented on product-web-app/service/authService.ts
> +      const response = await axios.post(`${this.API_URL}/auth/login`, login);
it will be easier when API will return it as a body

2023-08-10 13:39 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/db/AuthDao.java
> +    public void insertToken(String jwtToken, String email, long expiry) throws FailedToInsertTokenException {
not needed

2023-08-10 13:41 UTC, leszekgu commented on product-web-app/service/authService.ts
> +  async login(login: Login): Promise<string> {
where is a test method for this?

2023-08-10 16:14 UTC, japilarski commented on product-backend/src/main/java/org/kainos/ea/db/AuthDao.java
> +    public Token getToken(String email) throws FailedToGetTokenException {
I wanted to add a session verification. That's why I add tokens to DB. If you don't find it helpful, I will delete this feature from API and DB.

2023-08-10 16:17 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/db/AuthDao.java
> +    public Token getToken(String email) throws FailedToGetTokenException {
we can talk about that on Friday, but overall only verification needed should be based on JWT token and your secret value

2023-08-10 16:17 UTC, japilarski commented on product-backend/src/main/java/org/kainos/ea/resources/AuthController.java
> +            return Response.ok("JWT token").cookie(jwtCookie).build();
Passing a token as a response cookie was Łukasz J suggestion.

2023-08-10 16:18 UTC, japilarski commented on product-backend/src/test/java/service/AuthServiceTest.java
> +        assertEquals(result, jwtToken);
Already fixed.

2023-08-11 08:03 UTC, leszekgu approved these changes
ready to test from my perspective

2023-08-11 08:03 UTC, leszekgu commented on product-backend/src/test/java/service/AuthServiceTest.java
> +                .withIssuedAt(new Date(currentTime))
👍

2023-08-11 08:40 UTC, ljercha commented on product-backend/pom.xml
> +        </dependency>
JUnit 5 was already there 
```suggestion
```

2023-08-11 08:40 UTC, ljercha commented on product-backend/pom.xml
> +        </dependency>
Do you still need powermock? I don't see any usage.

```suggestion
```

2023-08-11 08:40 UTC, ljercha commented on product-web-app/tests/AuthService.test.ts
> +      }
Move assertions to finally block to make sure they are always executed.
```suggestion
     } finally {
        expect(errorMessage).to.equal('Login failed! Please try again.');
      }
```

2023-08-11 08:49 UTC, ljercha approved these changes

2023-08-11 15:10 UTC, merged