Feature/us012
kamil3197/agile-project-TEAMB pull request #13
Opened 2023-08-10 11:48 UTC by kamil3197

2023-08-10 16:16 UTC, leszekgu requested changes

2023-08-10 16:16 UTC, leszekgu commented on .idea/uiDesigner.xml
again?

2023-08-10 16:16 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/api/JobRoleService.java
> +    private static JobRoleDao jobRoleDao;
why static? I don't see a good reason

2023-08-10 16:16 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/api/JobRoleService.java
> +            return roleID.orElseThrow(() -> new FailedToCreateJobRoleException());
why just roleID is check and specID is not?

2023-08-10 16:16 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/db/JobRoleDao.java
> +        String insertStatement = "INSERT INTO Specifications (summary, sharepoint_link) VALUES (?, ?)";
this is missing a relationship with role table

2023-08-10 16:16 UTC, leszekgu commented on product-web-app/controller/JobRolesController.ts
> +          res.locals.successmessage = 'Success to add job role';
'Successfuly added a job role'

2023-08-10 16:16 UTC, leszekgu commented on product-web-app/controller/JobRolesController.ts
> +        res.locals.errormessage = 'Failed to add job role';
it might be useful to add here an error log / console.error ? with details from 'e' of why it failed, what status was returned

2023-08-10 16:16 UTC, leszekgu commented on product-web-app/service/jobRolesService.ts
> +      return response.status;
why do you return here http status?
your frontend Controller code is ignoring this value.
Backend is sending text with id - and maybe it doesn't have to if it's ignored.

2023-08-10 16:16 UTC, leszekgu commented on product-web-app/service/jobRolesService.ts
> +      throw new Error('Could not create job role');
it might be good to pass or check why server failed in adding a job-role, was it validation or API server failure, or it's a duplicate?

2023-08-11 07:41 UTC, ljercha reviewed
REFORMAT JAVA FILES AND REMOVE EXTRA BLANK LINES

2023-08-11 07:41 UTC, ljercha commented on product-web-app/views/add-job-roles.html
> +                <form action="/admin/job-roles" method="post">
```suggestion
                <h2>Enter job role details</h2>
                {% if successMessage %}
                <div class="alert alert-success" role="alert">{{successMessage}}</div>
                {% endif %}

                {% if errorMessage %}
                <div class="alert alert-danger" role="alert">{{errorMessage}}</div>
                {% endif %}
                <form action="/admin/job-roles" method="post">
```

2023-08-11 07:41 UTC, ljercha commented on product-web-app/views/add-job-roles.html
> +                    <h1>JobRole</h1>
```suggestion
                    <h1>Job Role</h1>
```

2023-08-11 07:41 UTC, ljercha commented on product-web-app/views/add-job-roles.html
> +    <title>add JobRole</title>
```suggestion
    <title>Add a new Job Role</title>
```

2023-08-11 07:41 UTC, ljercha commented on product-web-app/views/add-job-roles.html
> +                        <label for="title">Job role title</label>
```suggestion
                        <label for="title">Title</label>
```

2023-08-11 07:41 UTC, ljercha commented on product-web-app/model/addJobRole.ts
> +  sharepoint_link?: string;
https://github.com/airbnb/javascript#naming-conventions
```suggestion
  sharepointLink?: string;
```

2023-08-11 07:41 UTC, ljercha commented on product-web-app/model/addJobRole.ts
> +export interface AddJobRole {
```suggestion
export interface JobRole {
```

2023-08-11 07:41 UTC, ljercha commented on product-backend/src/test/java/org/kainos/ea/service/AddJobRoleServiceTest.java
> +public class AddJobRoleServiceTest {
```suggestion
public class JobRoleServiceTest {
```

2023-08-11 07:41 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/cli/AddJobRole.java
> +public class AddJobRole {
```suggestion
public class JobRole {
```

2023-08-11 07:41 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/resources/JobRoleController.java
> +                    .build();
```suggestion
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("Failed to create job role")
                    .build();
```

2023-08-11 07:41 UTC, ljercha commented on product-backend/src/test/java/org/kainos/ea/service/AddJobRoleServiceTest.java
> +
You should verify mocks have been called with proper parameters and expected amount of calls.
```suggestion
        int result = jobRoleService.createJobRole(addJobRole);
        verify(jobRoleDao).createRole(addJobRole);
        verify(jobRoleDao).createSpec(addJobRole);

```

2023-08-11 07:41 UTC, ljercha commented on product-backend/src/test/java/integration/AddJobRoleIT.java
> +    public void postJobRoles_shouldReturn500() {
should be 400 after the changes

2023-08-14 12:00 UTC, leszekgu requested changes

2023-08-14 12:00 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/api/JobRoleService.java
> +    private static JobRoleDao jobRoleDao;
its still here as static

2023-08-14 12:00 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/api/JobRoleService.java
> +                throw new FailedToCreateJobRoleException();
first check if roleId isPesent() if it's not throw exception,
then check kif specID is Present - if it's not then, remove role and only then throw exception

2023-08-14 12:00 UTC, leszekgu commented on product-web-app/service/jobRolesService.ts
> +      throw new Error('Could not create job role');
have you made any changes to the above?

2023-08-14 13:49 UTC, leszekgu approved these changes
ready to test from my perspective

2023-08-16 09:35 UTC, merged