UI/automation/test
kamil3197/agile-project-TEAMB pull request #22
Opened 2023-08-16 12:45 UTC by kacper-qa

UI automatic test created for registration and login.

2023-08-16 15:02 UTC, leszekgu commented on product-backend/scripts/create_db_local_exe.sql
will catch up with you about this in the morning. Long story short do `git rm example_data_local_exe.sql && git rm create_db_local_exe_sql`

2023-08-16 15:03 UTC, leszekgu commented on ui-test/test/pageobjects/login.ts
> +async fillLoginForm(email, password) {
missing indentation

2023-08-16 15:07 UTC, leszekgu requested changes
few syntax issues and in many places you've missed 'expect' method

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/pageobjects/login.ts
> +
empty line not needed

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/pageobjects/register.page.ts
> +async fillRegistrationForm(email, password, isAdmin: boolean) {
missing indentation

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/pageobjects/view-job-roles.page.ts
> +
please remove those empty lines, zero or one would be enough

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/specs/add-and-view-job-role.e2e.ts
> +  describe('Job Role Viewing Process', () => {
here indentation to the left (too many spaces or tabs) and whole describe block (lines 4-10)

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/specs/register.e2e.ts
> +      await RegisterPage.submitRegistrationForm();
where is the 'expect' part?

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/specs/login.e2e.ts
> +      await browser.pause(5000);
missing expect part

2023-08-16 15:07 UTC, leszekgu commented on ui-test/test/specs/view-job-roles.e2e.ts
> +
missing expect part

2023-08-17 07:55 UTC, kacper-qa commented on product-backend/scripts/create_db_local_exe.sql
Hi, 

From specs below files have been deleted:
- view-job-roles, 
- login, 
- register
- add-and-view-job-roles
From page objects below file has been deleted:
- view-job-roles

Instead we got one specs file "register_login_user" for test cases HappyPath, unHappyPath for registration and login e2e.

2023-08-17 15:11 UTC, leszekgu approved these changes

2023-08-17 15:11 UTC, merged