feature/US001-view-job-roles
kamil3197/agile-project-TEAMB pull request #6
Opened 2023-08-03 10:10 UTC by japilarski

2023-08-03 12:25 UTC, ljercha requested changes

2023-08-03 12:25 UTC, ljercha commented on agile-project-TEAMB.git/packed-refs
> +# pack-refs with: peeled fully-peeled sorted
What is that 👀 
I think you should get rid of that fork connection and clone repo to a separated one.

2023-08-03 21:09 UTC, leszekgu requested changes
whole directory 'agile-project-TEAMB.git' should be added to .gitignore and not part of this commit

2023-08-03 21:09 UTC, leszekgu commented on product-backend/scripts/US001.sql
> +	jobRoleId INT primary key AUTO_INCREMENT,
For sql columns please use snake_case https://en.wikipedia.org/wiki/Naming_convention_(programming)
Also it looks like there is a whitespace issue
Plus please align to structure from P002

2023-08-03 21:09 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/resources/JobRoleController.java
> +@Api("Employees API")
This whole file still refers to employees in multiple places

2023-08-03 21:09 UTC, leszekgu commented on product-web-app/service/jobRolesService.test.ts
> +            // console.log('________________________________________')
comments can be removed if functionality is finished here

2023-08-03 21:09 UTC, leszekgu commented on product-web-app/service/jobRolesService.test.ts
You are missing a case from acceptance criteria of having an empty list returned by API

2023-08-03 21:09 UTC, leszekgu commented on product-web-app/service/jobRolesService.test.ts
> +            mock.onGet(jobRolesService['API_URL'] + 'job-roles').reply(500);
Is this really working? it differs  from line 19 on concatenation

2023-08-03 21:09 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/api/JobRoleService.java
I would like to see UnitTests for this class, happy path, exception and empty list coming from db

2023-08-04 09:02 UTC, ljercha requested changes

2023-08-04 09:02 UTC, ljercha commented on .gitignore
> +agile-project-TEAMB.git
is it needed?

2023-08-04 09:02 UTC, ljercha commented on product-backend/scripts/US001_create_db.sql
> +CREATE DATABASE TeamA_JakubP;
schema name should be generic

2023-08-04 09:02 UTC, ljercha commented on product-backend/scripts/US001_example_data.sql
> +insert into JobRoles(job_role_title) values
scripts should not have the ticket number, use other ordering/counting way.

2023-08-04 09:02 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/DropwizardWebServiceApplication.java
> +        environment.jersey().register(RolesAllowedDynamicFeature.class);
what is that
```suggestion
```

2023-08-04 09:02 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/resources/JobRoleController.java
> +    private JobRoleDao jobRoleDao = new JobRoleDao();
not used
```suggestion
```

2023-08-04 09:02 UTC, ljercha commented on product-web-app/controller/JobRolesController.ts
> +            // if (jobRoles.length=0) {
remove comments

2023-08-04 09:02 UTC, ljercha commented on product-web-app/service/jobRolesService.ts
> +
run ESLint to fix formatting, empty lines etc.
```
npm run lint
```

2023-08-04 12:32 UTC, ljercha reviewed
Few minors looks promising

2023-08-04 12:32 UTC, ljercha commented on product-web-app/package.json
> +    "axios-mock-adapter": "^1.21.5",
Should be in devDependencies (run npm install after and commit package lock)

2023-08-04 12:32 UTC, ljercha commented on product-backend/scripts/US001_create_db.sql
> +CREATE DATABASE TeamA_JakubP;
Did you apply the fix/convention from P002?

2023-08-04 13:01 UTC, leszekgu requested changes
Looks better apply this one more change from me and some from Łukasz and soon it will go to testing

2023-08-04 13:01 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/resources/JobRoleController.java
> +    public Response getAllEmployees() {
why do you want to getEmployees? also employee is used in few other places in this class

2023-08-07 08:32 UTC, ljercha commented on product-web-app/package.json
> +    "axios-mock-adapter": "^1.21.5",
@japilarski  move it, run npm install and commit package-lock.json

2023-08-07 14:10 UTC, ljercha approved these changes

2023-08-09 08:03 UTC, IamGalexing approved these changes

2023-08-09 08:52 UTC, leszekgu commented on product-backend/scripts/create_db.sql
> +select * from JobRoles;
that's not needed

2023-08-09 08:53 UTC, japilarski commented on product-backend/scripts/create_db.sql
> +select * from JobRoles;
fixed

2023-08-09 08:54 UTC, leszekgu approved these changes

2023-08-09 08:58 UTC, merged