Feature/us014
kamil3197/agile-project-TEAMB pull request #8
Opened 2023-08-04 10:06 UTC by kamil3197

2023-08-04 13:23 UTC, leszekgu requested changes
Your commit names vary in standard (missing feat: ), please watch it.

2023-08-04 13:23 UTC, leszekgu commented on .idea/uiDesigner.xml
.idea/uiDesigner.xml should be on .gitignore list and probably `git rm --cached` is needed

2023-08-04 13:23 UTC, leszekgu commented on product-backend/scripts/Admin.sql
> +        level VARCHAR(255) NOT NULL,
level doesn't have to be so big, single Char would be enough

2023-08-04 13:23 UTC, leszekgu commented on product-backend/scripts/Admin.sql
> +        name VARCHAR(255) NOT NULL,
quite probably name should be unique

2023-08-04 13:23 UTC, leszekgu commented on product-backend/scripts/Admin.sql
> +	INSERT INTO Band (name, level, responsibilities) VALUES
with P002 this should probably be moved to separate file, check with Jakub, plus I'm not sure if it will work at first try, when it's in the same transaction as CREATE table

2023-08-04 13:23 UTC, leszekgu commented on product-backend/src/main/java/org/kainos/ea/resources/AdminController.java
> +            return Response.ok(adminService.createBand(admin)).build();
this should return HTTP_STATUS 201 you can use method `.status(Response.Created)` or something similar

2023-08-04 13:23 UTC, leszekgu commented on product-backend/src/test/java/service/adminServiceTest.java
> +public class adminServiceTest {
Class and file name should start from Upper case

2023-08-04 13:23 UTC, leszekgu commented on product-backend/src/test/java/integration/AdminIntegrationTest.java
> +    public void postBand_shouldReturn200() {
👍 for integration test

2023-08-04 13:23 UTC, leszekgu commented on product-backend/src/test/java/service/adminServiceTest.java
> +    Connection conn;
this is not used

2023-08-04 13:23 UTC, leszekgu commented on product-backend/src/test/java/service/adminServiceTest.java
product-backend/src/test/java/service/adminServiceTest.java please also add tests for unhappy path (-1) and sqlException handling

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/app.ts
> +    band: Partial<Band>;
not needed (band) can be removed

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/controller/bandController.ts
> +      console.error(e);
if there is an error like validation issue I would like the user to receive a message on the form and still have it's form populated with previously entered data

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/service/bandService.ts
> +    const response = await axios.post('http://localhost:8080/api/admin/band', band);
don't use hardcoded api host

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/tests/bandService.test.ts
> +    it('should return error 500 when could not create employee', async () => {
why 'employee' ?

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/tests/bandService.test.ts
> +  describe('addBand', () => {
please also add happy path :)

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/tests/bandValidator.test.ts
> +  describe('validateBand', () => {
Please also check for level to be (0-9)

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/validator/bandValidator.ts
> +  if (band.level.length < 1) {
level must be also at most 1 character (0-9)

2023-08-04 13:23 UTC, leszekgu commented on product-web-app/views/add-band.html
> +                <button type="submit" class="btn btn-primary" onclick="showConfirmation()">Submit</button>
onclick="showConfirmation() that will result in confirmation message even if it's gonna fail on backend. You need to add a different way - have a look at how errors were shown in workshops and update it for success messages

2023-08-04 13:35 UTC, ljercha commented on product-backend/.gitignore
> +db.properties
You do not have such a file. The boilerplate was using environment variables.
```suggestion

```

2023-08-04 13:35 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/db/AdminDao.java
> +    }
If you want to do it in a bit more elegant way you can use Optionals
For primitive types there are separate classes e.g. OptionalInt
https://docs.oracle.com/javase/8/docs/api/java/util/OptionalInt.html


```suggestion
    public OptionalInt createBand(Admin admin) throws SQLException {
        Connection c = databaseConnector.getConnection();


        String insertStatement = "INSERT INTO Band (name, level, responsibilities) VALUES (?, ?, ?)";

        PreparedStatement st = c.prepareStatement(insertStatement, Statement.RETURN_GENERATED_KEYS);

        st.setString(1, admin.getName());
        st.setString(2, admin.getLevel());
        st.setString(3, admin.getResponsibilities());


        st.executeUpdate();

        ResultSet rs = st.getGeneratedKeys();

        if (rs.next()) {
            return OptionalInt.of(rs.getInt(1));
        }
        return Optional.empty();
    }
```

Then in the AdminService you do
```
try {
            OptionalInt id = adminDao.createBand(admin);

            return id.orElseThrow();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
            throw new FailedToCreateBandException();
        } catch (NoSuchElementException e) {
            throw new FailedToCreateBandException(e);
        }
```

2023-08-04 13:35 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/resources/AdminController.java
> +public class AdminController {
Rename AdminController to BandController, apply it to DAO and frontend classes
```suggestion
public class BandController {
```

2023-08-04 13:35 UTC, ljercha commented on product-web-app/validator/bandValidator.ts
> +function validateBand(band: Band): string | null {
move to class

2023-08-04 13:35 UTC, ljercha commented on product-web-app/service/bandService.ts
> +const addBand = async (band: Band): Promise<Band> => {
move to class

2023-08-04 13:35 UTC, ljercha commented on product-web-app/package.json
> +    "start": "npx tsc && cp -R views dist && node dist/app.js",
its  already included in in _prestart_

2023-08-04 13:35 UTC, ljercha commented on product-web-app/package.json
> +    "start": "npx tsc && cp -R views dist && node dist/app.js",
https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts

2023-08-04 13:35 UTC, ljercha commented on product-web-app/controller/bandController.ts
> +      console.error(e);
do not disable it, fix it
```suggestion
    try {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      await addBand(data);
    } catch (e) {
      // eslint-disable-next-line no-console
      console.error(e);
```

2023-08-04 13:35 UTC, ljercha commented on product-web-app/controller/bandController.ts
> +export default function bandController(app: Application) {
move to class

2023-08-04 13:35 UTC, ljercha commented on product-backend/src/test/java/service/adminServiceTest.java
> +
please remove empty lines and reformat files.

2023-08-04 13:35 UTC, ljercha commented on product-backend/src/test/java/service/adminServiceTest.java
> +public class adminServiceTest {
```suggestion
public class AdminServiceTest {
```

2023-08-04 22:06 UTC, kamil3197 commented on product-backend/scripts/Admin.sql
> +	INSERT INTO Band (name, level, responsibilities) VALUES
In empty schema i can run this script with create and insert as one and it's working properly

2023-08-07 14:19 UTC, ljercha commented on .idea/uiDesigner.xml
Still there

2023-08-07 14:19 UTC, ljercha commented on product-backend/pom.xml
> +        <dependency>
It's already there see line 96

2023-08-07 14:19 UTC, ljercha commented on product-backend/pom.xml
> +        <dependency>
What is that?

2023-08-07 14:19 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/api/AdminService.java
> +    public DatabaseConnector databaseConnector;
not used

2023-08-08 10:38 UTC, ljercha commented on product-backend/pom.xml
> +        <dependency>
Remove

2023-08-09 06:55 UTC, ljercha approved these changes
Rename Admin to Band, expect that lgtm

2023-08-09 06:55 UTC, ljercha commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
![image](https://github.com/kamil3197/agile-project-TEAMB/assets/9252363/65f5de44-0819-483d-b553-c0266b857568)

2023-08-09 06:55 UTC, ljercha commented on product-backend/scripts/db_build.sh
> +mysql -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} ${db_name} < admin.sql
Rename file to band
```suggestion
mysql -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} ${db_name} < band.sql
```

2023-08-09 06:55 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/api/AdminService.java
> +public class AdminService {
```suggestion
public class BandService {
```

2023-08-09 06:55 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/cli/Admin.java
> +public class Admin {
```suggestion
public class Band {
```

2023-08-09 06:55 UTC, ljercha commented on product-backend/src/main/java/org/kainos/ea/cli/validator/AdminValidator.java
> +public class AdminValidator {
```suggestion
public class BandValidator {
```

2023-08-09 06:55 UTC, ljercha commented on product-backend/src/test/java/integration/AdminIT.java
> +public class AdminIT {
```suggestion
public class BandIT {
```

2023-08-09 07:41 UTC, bitguna approved these changes
Code review approveed

2023-08-09 14:04 UTC, leszekgu approved these changes

2023-08-10 14:08 UTC, merged